FROM php:8.1-apache

# تثبيت mysqli حيت السكربت كيحتاج يتكونيكطا مع الداتابيز
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli

# نسخ الكود للمجلد الرئيسي
COPY . /var/www/html/

# إعطاء الصلاحيات (Permission Fix)
RUN chown -R www-data:www-data /var/www/html

EXPOSE 80